---
- name: Installing Python dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools
    # python-mysql for collectd
    - python-mysqldb
    - python-pip

- name: Installing libpq
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libpq-dev

- name: Install some python bindings
  pip:
    name: "{{ item }}"
  with_items:
    # version important because 3.0 doesn't work with current version of enoslib
    - docker==2.7.0
    - influxdb
    - psycopg2
    - flent

- name: Mount /run
  command: mount --make-shared /run
